### ISSUE TITLE
super-user-application jar is not working for Window 8.1

### ISSUE THREAD

**Issue by umesh-m-jadhav** [rritoch/super-user-application#6]
Hi Ralph,

Our Jar is working fine on Window 7 but not working for Window 8.1 
I debugged code, 

in WinSudo.java, Line 165- boolean result = Shell32X.INSTANCE.ShellExecuteEx(execInfo);

This line is not opening the User account control popup. But in Window 7, this line open the popup and after clicking yes, further processing working fine.

Could you please help? Also let us know if you need more detail about the issue?

**Comment by rritoch** [comment]
umesh-m-jadhav,

This sounds like  an operating system bug, you should consult Microsoft about the issue.  

This has been tested on windows 8.1 machines and worked. 

It is possible that you have the UAC popup disabled on that machine.  The documentation is at https://msdn.microsoft.com/en-us/library/windows/desktop/bb762154(v=vs.85).aspx and the "runas" verb set on line 154 is what causes the UAC to open. 

See : https://github.com/rritoch/super-user-application/blob/master/src/main/java/com/vnetpublishing/java/suapp/win/WinSudo.java#L164

This was previously tested on windows 8.1 and was fully functional so if it isn't working than there is likely a windows update that broke the functionality but the code itself is compliant with the official documentation.

**Comment by rritoch** [comment]
umesh-m-jadhav,

See http://ccm.net/faq/30236-windows-8-1-disable-the-uac-user-account-control for more details on how the UAC can be disabled in windows 8.1 which is likely what caused your problem.
