### ISSUE TITLE
Example for a Swing UI

### ISSUE THREAD

**Issue by spyhunter99** [rritoch/super-user-application#7]
I'm attempting to write an installer using a swing ui. The problem is that the swing ui is non blocking, therefore the `public int run(String[] args) {` exits immediately which kills the UI.  I'm not sure if there's a good way to handle this other than to have some kind of flag and to block the int run method until the flag is flipped (install done). Thoughts?

**Comment by rritoch** [comment]
I believe this should work with swing by placing the swing code in the run method instead of the main method and using an undocumented feature to prevent the system from exiting.

```
public int run(String[] args) {
	SU.setDaemon(true);
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
}
```

**Comment by spyhunter99** [comment]
That did the trick! awesome library
